### PR TITLE
Use bash from env for better portability

### PR DESCRIPTION
**Pull request by Luz**
Hi
According to [Stackoverflow](https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang#10383546) it looks like the portability of the scripts could be improved by having this new style for the bash shebang.

### CODE REVIEW

**Review by rnestler — APPROVED** [review]
Detected the NixOS user :wink: 

LGTM, but the Mac people should maybe also chime in?

**Comment by coorasse** [comment]
What issue are we trying to solve? Is there an existing problem?

**Comment by rnestler** [comment]
> What issue are we trying to solve? Is there an existing problem?

Read the linked stackoverflow: As is the scripts won't run on operating systems that put bash in a different place than `/bin/bash` (or don't symlink `/bin/bash` to the place where bash resides). Examples seem to be OpenBSD, FreeBSD, NixOS

**Review by coorasse — APPROVED** [review]
All right! On mac it works in both ways.

**Pull request merged**
