### PR TITLE
Fix selenium driver defaults

### PR DESCRIPTION
**Pull request by Janis-Leuenberger**

### CODE REVIEW

**Comment by schmijos** [comment]
Since you're already in the context: would you mind to switch the ASG to https://github.com/titusfortner/webdrivers entirely?

**Review by coorasse — APPROVED** [review]

**Review by sihu — APPROVED** [review]

**Review by Liberatys — APPROVED** [review]

**Comment by Janis-Leuenberger** [comment]
@schmijos you probably know more about this than I do. What exactly do you mean by switching entirely?

**Comment by schmijos** [comment]
> @schmijos you probably know more about this than I do. What exactly do you mean by switching entirely?

I'd adjust the ASG to use the `webdrivers` gem. (in a separate PR)

**Comment by Janis-Leuenberger** [comment]
For some reason I added `webdrivers` during the vista setup but I can't figure out why. It's not in the ASG.

**Pull request merged**
