### PR TITLE
Remove slim-lint

### PR DESCRIPTION
**Pull request by schmijos**
slim-lint doesn't autofix even the smallest issues which makes it a pain. So I suggest to remove it (or replace it with something that can autofix)

### CODE REVIEW

**Comment by schmijos** [comment]
Linters should make my life easier and not harder:

```
app/views/shared/_custom_flash_messages.html.slim:8 [W] LineLength: Line is too long. [122/120]
app/views/shared/_custom_flash_messages.html.slim:9 [W] TrailingBlankLines: Multiple empty lines in the end of file
app/views/shared/_default_flash_messages.html.slim:2 [W] RuboCop: Style/PercentLiteralDelimiters: `%w`-literals should be delimited by `[` and `]`.
app/views/shared/_default_flash_messages.html.slim:6 [W] TrailingBlankLines: Multiple empty lines in the end of file
```

Fo such a linter result I've to manually go to 4 different places in the code and correct one specific thing. That's not what I understand as an easy life.

**Comment by coorasse** [comment]
In such a case, without slim-lint, you would have committed a 122 chars long line, and a file with multiple blank lines. Wouldn't this be bad?

**Comment by sihu** [comment]
I am also more on the side of adding some autofixes for stupid findings

**Comment by schmijos** [comment]
@coorasse I agree that it's bad. But I am questioning how bad it really is. Is a shiny golden slim template worth the fuzz?

**Comment by coorasse** [comment]
some things are more important than others, a line longer than 120 characters is really annoying for example. 
we can, of course, discuss the single rules, but if the topic is a generic "yes/no to slim linting" I am for a yes: it helps me write better templates and keep them clean. 
If a reviewer would have noticed the above four things, commented, requested changes, etc... the fuzz would have been way bigger.

**Comment by schmijos** [comment]
FYI: I started a thread here to feel the software engineering community outside of our bubble: https://softwareengineering.stackexchange.com/questions/396194/does-linting-without-auto-correction-make-sense

**Comment by coorasse** [comment]
👍 for an opening to StackExchange. is a very good idea to get a different point of view.

**Pull request closed without merging**
