### PR TITLE
add migration command to deploy script

### PR DESCRIPTION
**Pull request by pandermatt**

### CODE REVIEW

**Review by macav — APPROVED** [review]
aren't these templates also in the `renuo-cli`?

**Comment by pandermatt** [comment]
I just checked, but they are not in the cli

**Comment by coorasse** [comment]
@pandermatt https://github.com/renuo/renuo-cli/blob/master/lib/renuo/cli/app/templates/semaphore/semaphore-deploy.yml.erb

**Comment by pandermatt** [comment]
Ahh it's a erb file, that's why I didn't found it. Thx

**Comment by coorasse** [comment]
There's a search function, you can use for that 👍 
https://github.com/renuo/renuo-cli/search?q=git+push+heroku

**Pull request merged**
