### PR TITLE
Update node version specification

### PR DESCRIPTION
**Pull request by Janis-Leuenberger**
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

### CODE REVIEW

**Review by odthoma — APPROVED** [review]
Thanks 👍🏻 I'd maybe also add that you should only specify the major version. (e.g `16.x`) We should still keep the `.nvmrc` btw.

Also maybe that you'd have to add the nodejs buildpack on heroku in addition to the ruby one => in the correct order

(ah well i guess this is for the CI??)

**Comment by Janis-Leuenberger** [comment]
1. I agree on just adding the major version.
2. Why do you want to keep the `.nvmrc`?
3. Heroku will figure out the correct buildpack most of the time. In the other cases you will know soon enough.
4. This is for heroku.

Do we even need node in production?

**Review by schmijos — CHANGES_REQUESTED** [review]
Oi, Heroku is not to be mixed-up with Sempaphore:

> The version of Node.js that will be used can be set from a .nvmrc file, if such a file exists in your repository.

https://docs.semaphoreci.com/programming-languages/javascript-and-node-js/

**Comment by odthoma** [comment]
Well, AFAIK we decided upon still sticking to `.nvmrc` for specifying the node version instead of `.tool-versions`. Thus we should still keep it. I still want my version manager to automatically switch my node environment. And yes, we only need node to compile our assets on production I guess.

**Comment by Janis-Leuenberger** [comment]
So this part should be kept as is and add the changes to the application server setup instead?

Still we will have to specify the node version twice even if we go with the `nvmrc`. Opinions, solutions?

**Comment by coorasse** [comment]
`.nvmrc` is still needed locally and semaphore. isn't there a way to have heroku reading it as well? 🤷

**Comment by odthoma** [comment]
@coorasse I think we already talked about this once and didn't find a proper solution. But I mean how often do you really change the node version. Having to change it in 2 spots it not that bad.

We could maybe add a few lines to `bin/fastcheck` that would throw an error when the version in the `package.json` and in the `.nvmrc` are not lined up.

**Comment by coorasse** [comment]
@Janis-Leuenberger please find an agreement. and try to finalise this :)

**Pull request closed without merging**
