### PR TITLE
Disable cop

### PR DESCRIPTION
**Pull request by coorasse**
https://docs.rubocop.org/rubocop/cops_style.html#stylehashaslastarrayitem
I don't like to add syntax sugar if not needed. The "no_braces" option doesn't work well if you have an array of hashes. see #242

### CODE REVIEW

**Review by macav — APPROVED** [review]

**Review by schmijos — CHANGES_REQUESTED** [review]
@coorasse I agree with the issues you have with `no_braces`, but I'd be in favor of `braces` because I find everything else to be error-prone.

**Comment by coorasse** [comment]
what do you mean with "error prone"? what kind of error can be made?

**Comment by coorasse** [comment]
@sihu any opinion on the topic? Otherwise I will just go for a 2v1 win and merge it 😄

**Comment by schmijos** [comment]
By error-prone, I mean that `[1, 2, one: 1, two: 2]` looks like it has 4 elements or that `[1, 2, one: 1, two: 2, 'three']` is invalid syntax. This cop set to `braces` helps us to make less errors.

**Review by sihu — APPROVED** [review]

**Comment by coorasse** [comment]
I'll just go by majority. Thank you all 🙏

**Pull request merged**
